name: quizblitz
description: A Kahoot-style quiz game built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6

  # HTTP Client
  dio: ^5.4.3

  # Navigation
  go_router: ^14.2.0

  # Dependency Injection
  get_it: ^7.7.0

  # Local Storage
  shared_preferences: ^2.3.1

  # Supabase Storage
  supabase_flutter: ^2.5.6

  # Image Picker
  image_picker: ^1.1.2

  # Google Fonts
  google_fonts: ^6.2.1

  # Equatable
  equatable: ^2.0.5

  # Cached Network Image
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.8
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
