import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;
  const AppLocalizations(this.locale);

  static const supportedLocales = [
    Locale('en'),
    Locale('fr'),
    Locale('ar'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'createQuiz': 'Create Quiz',
      'editQuiz': 'Edit Quiz',
      'joinGame': 'Join Game',
      'make': 'Make',
      'myQuizzes': 'My Quizzes',
      'player': 'Player',
      'profile': 'Profile',
      'language': 'Language',
      'theme': 'Theme',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'english': 'English',
      'french': 'French',
      'arabic': 'Arabic',
      'welcomeBack': 'Welcome back!',
      'createAccount': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'username': 'Username',
      'signUp': 'Sign up',
      'logIn': 'Log In',
      'alreadyHaveAccount': 'Already have an account?',
      'dontHaveAccount': 'Don\'t have an account?',
      'correct': 'Correct!',
      'wrong': 'Wrong!',
      'waitingForOthers': 'Waiting for others…',
      'homeCreateToolsTitle': 'Create your own: quick tools to get started',
      'noQuizzesCreatedYet': 'You haven\'t created any quizzes yet.',
      'questionsCount': '{count} questions',
      'hostGame': 'Host Game',
      'edit': 'Edit',
      'delete': 'Delete',
      'deleteQuizTitle': 'Delete Quiz',
      'deleteQuizConfirm': 'Delete "{title}"? This cannot be undone.',
      'cancel': 'Cancel',
      'retry': 'Retry',
      'createContentFromScratch': 'Create content from scratch',
      'createWithAi': 'Save time! Create with AI',
      'createFromStudyNotes': 'Quickly create from study notes',
      'createFromPresentation': 'Turn presentations into engaging experiences',
      'generateWithAi': 'Generate with AI',
      'enterTopicHint': 'Enter a topic (e.g. History of Rome)',
      'generate': 'Generate',
      'generatingQuizWithAi': 'Generating quiz with AI...',
      'uploadingPdf': 'Uploading PDF...',
      'uploadingPresentation': 'Uploading Presentation...',
      'errorMessage': 'Error: {error}',
      'couldNotReadFileData': 'Could not read file data.',
      'logout': 'Log out',
      'uploadFailed': 'Upload failed: {error}',
      'profileUpdated': 'Profile updated',
      'saveChanges': 'Save Changes',
      'editProfile': 'Edit Profile',
      'yourStats': 'Your Stats',
      'quizzesCreated': 'Quizzes\nCreated',
      'gamesPlayed': 'Games\nPlayed',
      'bestRank': 'Best\nRank',
      'hostLogin': 'Host / Login',
      'noGameFoundWithPin': 'No game found with this PIN',
      'pleaseEnterNickname': 'Please enter a nickname',
      'gamePin': 'Game PIN',
      'enter': 'Enter',
      'chooseAvatar': 'Choose Avatar',
      'nickname': 'Nickname',
      'okGo': 'OK, go!',
      'finalResults': 'Final Results',
      'exit': 'Exit',
      'nextQuestion': 'Next Question',
      'waitingForHost': 'Waiting for host…',
      'standby': 'Standby…',
      'congratulations': 'Congratulations!',
      'youWonTheGame': 'You won the game! Amazing performance!',
      'goodLuckNextTime': 'Good luck next time!',
      'youFinishedRank': 'You finished at #{rank}. Keep practicing!',
      'winner': 'Winner',
      'runnerUp': 'Runner-up',
      'thirdPlace': '3rd Place',
      'pointsShort': '{points} pts',
      'allQuizzes': 'All Quizzes',
      'noQuizzesFound': 'No quizzes found.',
      'public': 'Public',
      'private': 'Private',
      'hostThisQuiz': 'Host This Quiz',
      'questions': 'Questions',
      'questionCountLabel': 'Questions ({count})',
      'quizCreated': 'Quiz created!',
      'quizUpdated': 'Quiz updated!',
      'save': 'Save',
      'addCoverImage': 'Add Cover Image',
      'quizTitle': 'Quiz Title',
      'quizTitleHint': 'e.g. World Geography',
      'titleRequired': 'Title is required',
      'descriptionOptional': 'Description (optional)',
      'quizDescriptionHint': 'A short description of this quiz',
      'publicQuiz': 'Public Quiz',
      'visibleToEveryone': 'Visible to everyone',
      'visibleOnlyToYou': 'Only visible to you',
      'addQuestion': 'Add Question',
      'addAtLeastOneQuestion': 'Add at least one question.',
      'questionHasNoText': 'Question {index} has no text.',
      'questionNeedsCorrectAnswer':
          'Question {index} needs at least one correct answer.',
      'questionText': 'Question text',
      'timeSeconds': 'Time: {seconds}s',
      'changeImage': 'Change image',
      'addImage': 'Add image',
      'answersTapToMarkCorrect': 'Answers (tap ✓ to mark correct)',
      'answerHint': 'Answer {index}',
    },
    'fr': {
      'createQuiz': 'Créer un quiz',
      'editQuiz': 'Modifier le quiz',
      'joinGame': 'Rejoindre une partie',
      'make': 'Créer',
      'myQuizzes': 'Mes quiz',
      'player': 'Joueur',
      'profile': 'Profil',
      'language': 'Langue',
      'theme': 'Thème',
      'system': 'Système',
      'light': 'Clair',
      'dark': 'Sombre',
      'english': 'Anglais',
      'french': 'Français',
      'arabic': 'Arabe',
      'welcomeBack': 'Bon retour !',
      'createAccount': 'Créer un compte',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'confirmPassword': 'Confirmer le mot de passe',
      'username': 'Nom d\'utilisateur',
      'signUp': 'S\'inscrire',
      'logIn': 'Se connecter',
      'alreadyHaveAccount': 'Vous avez déjà un compte ?',
      'dontHaveAccount': 'Vous n\'avez pas de compte ?',
      'correct': 'Correct !',
      'wrong': 'Faux !',
      'waitingForOthers': 'En attente des autres…',
      'homeCreateToolsTitle': 'Créez le vôtre : outils rapides pour commencer',
      'noQuizzesCreatedYet': 'Vous n\'avez encore créé aucun quiz.',
      'questionsCount': '{count} questions',
      'hostGame': 'Animer la partie',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'deleteQuizTitle': 'Supprimer le quiz',
      'deleteQuizConfirm': 'Supprimer "{title}" ? Cette action est irréversible.',
      'cancel': 'Annuler',
      'retry': 'Réessayer',
      'createContentFromScratch': 'Créer du contenu depuis zéro',
      'createWithAi': 'Gagnez du temps ! Créez avec l\'IA',
      'createFromStudyNotes': 'Créer rapidement à partir de notes de cours',
      'createFromPresentation': 'Transformer des présentations en expériences engageantes',
      'generateWithAi': 'Générer avec l\'IA',
      'enterTopicHint': 'Entrez un sujet (ex. : Histoire de Rome)',
      'generate': 'Générer',
      'generatingQuizWithAi': 'Génération du quiz avec l\'IA...',
      'uploadingPdf': 'Téléversement du PDF...',
      'uploadingPresentation': 'Téléversement de la présentation...',
      'errorMessage': 'Erreur : {error}',
      'couldNotReadFileData': 'Impossible de lire les données du fichier.',
      'logout': 'Se déconnecter',
      'uploadFailed': 'Échec du téléversement : {error}',
      'profileUpdated': 'Profil mis à jour',
      'saveChanges': 'Enregistrer les modifications',
      'editProfile': 'Modifier le profil',
      'yourStats': 'Vos statistiques',
      'quizzesCreated': 'Quiz\ncréés',
      'gamesPlayed': 'Parties\njouées',
      'bestRank': 'Meilleur\nrang',
      'hostLogin': 'Animer / Connexion',
      'noGameFoundWithPin': 'Aucune partie trouvée avec ce PIN',
      'pleaseEnterNickname': 'Veuillez entrer un pseudo',
      'gamePin': 'PIN de partie',
      'enter': 'Entrer',
      'chooseAvatar': 'Choisir un avatar',
      'nickname': 'Pseudo',
      'okGo': 'OK, c\'est parti !',
      'finalResults': 'Résultats finaux',
      'exit': 'Quitter',
      'nextQuestion': 'Question suivante',
      'waitingForHost': 'En attente de l\'hôte…',
      'standby': 'En attente…',
      'congratulations': 'Félicitations !',
      'youWonTheGame': 'Vous avez gagné la partie ! Performance incroyable !',
      'goodLuckNextTime': 'Bonne chance pour la prochaine fois !',
      'youFinishedRank': 'Vous avez terminé à la position n°{rank}. Continuez à vous entraîner !',
      'winner': 'Gagnant',
      'runnerUp': 'Finaliste',
      'thirdPlace': '3e place',
      'pointsShort': '{points} pts',
      'allQuizzes': 'Tous les quiz',
      'noQuizzesFound': 'Aucun quiz trouvé.',
      'public': 'Public',
      'private': 'Privé',
      'hostThisQuiz': 'Animer ce quiz',
      'questions': 'Questions',
      'questionCountLabel': 'Questions ({count})',
      'quizCreated': 'Quiz créé !',
      'quizUpdated': 'Quiz mis à jour !',
      'save': 'Enregistrer',
      'addCoverImage': 'Ajouter une image de couverture',
      'quizTitle': 'Titre du quiz',
      'quizTitleHint': 'ex. : Géographie du monde',
      'titleRequired': 'Le titre est obligatoire',
      'descriptionOptional': 'Description (optionnelle)',
      'quizDescriptionHint': 'Une brève description de ce quiz',
      'publicQuiz': 'Quiz public',
      'visibleToEveryone': 'Visible par tout le monde',
      'visibleOnlyToYou': 'Visible uniquement par vous',
      'addQuestion': 'Ajouter une question',
      'addAtLeastOneQuestion': 'Ajoutez au moins une question.',
      'questionHasNoText': 'La question {index} n\'a pas de texte.',
      'questionNeedsCorrectAnswer':
          'La question {index} doit avoir au moins une bonne réponse.',
      'questionText': 'Texte de la question',
      'timeSeconds': 'Temps : {seconds}s',
      'changeImage': 'Changer l\'image',
      'addImage': 'Ajouter une image',
      'answersTapToMarkCorrect': 'Réponses (touchez ✓ pour marquer la bonne)',
      'answerHint': 'Réponse {index}',
    },
    'ar': {
      'createQuiz': 'إنشاء اختبار',
      'editQuiz': 'تعديل الاختبار',
      'joinGame': 'الانضمام إلى لعبة',
      'make': 'إنشاء',
      'myQuizzes': 'اختباراتي',
      'player': 'لاعب',
      'profile': 'الملف الشخصي',
      'language': 'اللغة',
      'theme': 'المظهر',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'english': 'الإنجليزية',
      'french': 'الفرنسية',
      'arabic': 'العربية',
      'welcomeBack': 'مرحبًا بعودتك!',
      'createAccount': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'username': 'اسم المستخدم',
      'signUp': 'إنشاء حساب',
      'logIn': 'تسجيل الدخول',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟',
      'dontHaveAccount': 'ليس لديك حساب؟',
      'correct': 'إجابة صحيحة!',
      'wrong': 'إجابة خاطئة!',
      'waitingForOthers': 'بانتظار الآخرين…',
      'homeCreateToolsTitle': 'أنشئ محتواك: أدوات سريعة للبدء',
      'noQuizzesCreatedYet': 'لم تقم بإنشاء أي اختبار بعد.',
      'questionsCount': '{count} أسئلة',
      'hostGame': 'استضافة اللعبة',
      'edit': 'تعديل',
      'delete': 'حذف',
      'deleteQuizTitle': 'حذف الاختبار',
      'deleteQuizConfirm': 'حذف "{title}"؟ لا يمكن التراجع عن هذا.',
      'cancel': 'إلغاء',
      'retry': 'إعادة المحاولة',
      'createContentFromScratch': 'أنشئ المحتوى من الصفر',
      'createWithAi': 'وفّر الوقت! أنشئ بالذكاء الاصطناعي',
      'createFromStudyNotes': 'أنشئ بسرعة من ملاحظات الدراسة',
      'createFromPresentation': 'حوّل العروض التقديمية إلى تجارب ممتعة',
      'generateWithAi': 'إنشاء بالذكاء الاصطناعي',
      'enterTopicHint': 'أدخل موضوعًا (مثال: تاريخ روما)',
      'generate': 'إنشاء',
      'generatingQuizWithAi': 'جارٍ إنشاء الاختبار بالذكاء الاصطناعي...',
      'uploadingPdf': 'جارٍ رفع ملف PDF...',
      'uploadingPresentation': 'جارٍ رفع العرض التقديمي...',
      'errorMessage': 'خطأ: {error}',
      'couldNotReadFileData': 'تعذر قراءة بيانات الملف.',
      'logout': 'تسجيل الخروج',
      'uploadFailed': 'فشل الرفع: {error}',
      'profileUpdated': 'تم تحديث الملف الشخصي',
      'saveChanges': 'حفظ التغييرات',
      'editProfile': 'تعديل الملف الشخصي',
      'yourStats': 'إحصاءاتك',
      'quizzesCreated': 'الاختبارات\nالمنشأة',
      'gamesPlayed': 'الألعاب\nالملعوبة',
      'bestRank': 'أفضل\nترتيب',
      'hostLogin': 'استضافة / تسجيل الدخول',
      'noGameFoundWithPin': 'لم يتم العثور على لعبة بهذا الرمز',
      'pleaseEnterNickname': 'يرجى إدخال اسم مستعار',
      'gamePin': 'رمز اللعبة',
      'enter': 'دخول',
      'chooseAvatar': 'اختر صورة رمزية',
      'nickname': 'الاسم المستعار',
      'okGo': 'حسنًا، انطلق!',
      'finalResults': 'النتائج النهائية',
      'exit': 'خروج',
      'nextQuestion': 'السؤال التالي',
      'waitingForHost': 'بانتظار المضيف…',
      'standby': 'انتظار…',
      'congratulations': 'تهانينا!',
      'youWonTheGame': 'لقد فزت باللعبة! أداء رائع!',
      'goodLuckNextTime': 'حظًا أوفر في المرة القادمة!',
      'youFinishedRank': 'أنهيت اللعبة في المركز #{rank}. واصل التدريب!',
      'winner': 'الفائز',
      'runnerUp': 'الوصيف',
      'thirdPlace': 'المركز الثالث',
      'pointsShort': '{points} نقطة',
      'allQuizzes': 'كل الاختبارات',
      'noQuizzesFound': 'لم يتم العثور على اختبارات.',
      'public': 'عام',
      'private': 'خاص',
      'hostThisQuiz': 'استضافة هذا الاختبار',
      'questions': 'الأسئلة',
      'questionCountLabel': 'الأسئلة ({count})',
      'quizCreated': 'تم إنشاء الاختبار!',
      'quizUpdated': 'تم تحديث الاختبار!',
      'save': 'حفظ',
      'addCoverImage': 'إضافة صورة غلاف',
      'quizTitle': 'عنوان الاختبار',
      'quizTitleHint': 'مثال: جغرافيا العالم',
      'titleRequired': 'العنوان مطلوب',
      'descriptionOptional': 'الوصف (اختياري)',
      'quizDescriptionHint': 'وصف قصير لهذا الاختبار',
      'publicQuiz': 'اختبار عام',
      'visibleToEveryone': 'مرئي للجميع',
      'visibleOnlyToYou': 'مرئي لك فقط',
      'addQuestion': 'إضافة سؤال',
      'addAtLeastOneQuestion': 'أضف سؤالًا واحدًا على الأقل.',
      'questionHasNoText': 'السؤال {index} لا يحتوي على نص.',
      'questionNeedsCorrectAnswer':
          'يجب أن يحتوي السؤال {index} على إجابة صحيحة واحدة على الأقل.',
      'questionText': 'نص السؤال',
      'timeSeconds': 'الوقت: {seconds}ث',
      'changeImage': 'تغيير الصورة',
      'addImage': 'إضافة صورة',
      'answersTapToMarkCorrect': 'الإجابات (اضغط ✓ لتحديد الصحيحة)',
      'answerHint': 'الإجابة {index}',
    },
  };

  String t(String key, {Map<String, String>? params}) {
    var value =
        _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']![key] ?? key;
    if (params != null) {
      params.forEach((paramKey, paramValue) {
        value = value.replaceAll('{$paramKey}', paramValue);
      });
    }
    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales
          .any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension AppL10nX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
